character:
  name_generation:
    ancient:
      female_given:
      - 霞
      - 月
      - 花
      - 雪
      - 玉
      - 珠
      - 凤
      - 莲
      - 春
      - 秋
      female_middle:
      - 静
      - 婷
      - 美
      - 丽
      - 雅
      - 芳
      - 华
      - 英
      - 慧
      - 贤
      male_given:
      - 云
      - 风
      - 山
      - 河
      - 海
      - 天
      - 地
      - 星
      - 月
      - 日
      male_middle:
      - 子
      - 文
      - 武
      - 德
      - 明
      - 志
      - 仁
      - 义
      - 礼
      - 智
      surnames:
      - 李
      - 王
      - 张
      - 刘
      - 陈
      - 杨
      - 赵
      - 黄
      - 周
      - 吴
      titles:
      - 道长
      - 真人
      - 仙子
      - 大师
      - 前辈
    future:
      female_given:
      - 指挥官
      - 工程师
      - 探索者
      - 战士
      - 科学家
      - 领航员
      - 守护者
      - 研究员
      male_given:
      - 指挥官
      - 工程师
      - 探索者
      - 战士
      - 科学家
      - 领航员
      - 守护者
      - 研究员
      surnames:
      - 电子
      - 量子
      - 星际
      - 虚拟
      - 智能
      - 光速
      - 时空
      - 基因
      - 纳米
      - 脑波
      titles:
      - 指挥官
      - 博士
      - 教授
      - 研究员
      - 工程师
    modern:
      female_given:
      - 娟
      - 敏
      - 静
      - 秀
      - 丽
      - 艳
      - 芳
      - 萍
      - 英
      - 华
      male_given:
      - 伟
      - 强
      - 磊
      - 超
      - 勇
      - 军
      - 建
      - 光
      - 明
      - 永
      surnames:
      - 张
      - 王
      - 李
      - 赵
      - 钱
      - 孙
      - 周
      - 吴
      - 郑
      - 陈
      titles:
      - 先生
      - 女士
      - 老师
      - 博士
      - 教授
